//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMTVision.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.21.6/MESWS/Assembly/MatchLabel.asmx")]
        public string LMTVision_MBMatchLabel_MatchLabel {
            get {
                return ((string)(this["LMTVision_MBMatchLabel_MatchLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.49.6/MESWS/Assembly/MatchLabel.asmx")]
        public string LMTVision_JMBMatchLabel_MatchLabel {
            get {
                return ((string)(this["LMTVision_JMBMatchLabel_MatchLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.26/MESWS/Assembly/MatchLabel.asmx")]
        public string LMTVision_GlueMatchLabel_MatchLabel {
            get {
                return ((string)(this["LMTVision_GlueMatchLabel_MatchLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.21.6/MESWS/Assembly/Eqp_BPF.asmx")]
        public string LMTVision_BPFWeb_Eqp_BPF {
            get {
                return ((string)(this["LMTVision_BPFWeb_Eqp_BPF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.49.6/MESWS/Assembly/Eqp_BPF.asmx")]
        public string LMTVision_JBPFWebIn_Eqp_BPF {
            get {
                return ((string)(this["LMTVision_JBPFWebIn_Eqp_BPF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.49.6/MESWS/Assembly/MatchLabel.asmx")]
        public string LMTVision_JBPFWebOut_MatchLabel {
            get {
                return ((string)(this["LMTVision_JBPFWebOut_MatchLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.26/MESWS/Assembly/MatchLabel.asmx")]
        public string LMTVision_glueWebReference_MatchLabel {
            get {
                return ((string)(this["LMTVision_glueWebReference_MatchLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.26/mesws/Assembly/Eqp_LMT.asmx")]
        public string LMTVision_Web_Tray_InOut_Eqp_LMT {
            get {
                return ((string)(this["LMTVision_Web_Tray_InOut_Eqp_LMT"]));
            }
        }
    }
}
